# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.provision "shell", path: "provision.sh"
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.50.30", auto_config: false
    master.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "500"
        vb.cpus = 2
    end
  end



  (31..32).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.box = "ubuntu/bionic64"
      worker.vm.hostname = "node-#{i}"
      worker.vm.network "private_network", ip: "192.168.50.#{i}", auto_config: false
      worker.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "500"
	vb.cpus = 2
      end  

    end

  end


end


