# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "master-vm" do | vm1| 
      vm1.vm.hostname = "master-cluster"
      vm1.vm.box = "ubuntu/xenial64"
      vm1.vm.box_check_update = false
      vm1.vm.network "forwarded_port", guest: 80, host: 8080
      vm1.vm.network "private_network", ip: "10.0.20.100"

      vm1.vm.provision "shell", inline: <<-SHELL
        apt install g++ make 
        echo "Downloading MPICH Compiler From MPICH.ORG"
        wget http://www.mpich.org/static/downloads/3.3.2/mpich-3.3.2.tar.gz
        echo "extracting MPICH Compiler From MPICH.ORG"
        sleep 8 
        tar -xvf mpich-3.3.2.tar.gz
        cd mpich-3.3.2
        ./configure --enable-fast=O3,ndebug --disable-error-checking --without-timing --without-mpit-pvars --disable-fortran && make && make install
        which mpicc
        which mpiexec
        echo "Getting MPICC Version"
        mpicc --version 
      SHELL
  end
end
