# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "master-vm" do | vm1| 
      vm1.vm.hostname = "master-cluster"
      vm1.vm.box = "ubuntu/xenial64"
      vm1.vm.box_check_update = false
      vm1.vm.network "forwarded_port", guest: 80, host: 8080
      vm1.vm.network "private_network", ip: "10.0.20.100"

      vm1.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install mpich git -y 
        echo "Getting MPICC Version"
        mpicc --version 
      SHELL
  end
end
