# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell", path: "provision.sh"

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "10.11.12.50", auto_config: false
    master.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "500"
        vb.cpus = 2
    end
  end

  (51..53).each do |i|
    
    config.vm.define "worker-#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "node-#{i}"
      node.vm.network "private_network", ip: "10.11.12.#{i}", auto_config: false

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "300"
      end  
      
    end

  end

  
  
end
